pipeline {
    agent {
        dockerfile {
            dir '02'
        }
    }
    stages {
        stage('Verify') {
            steps {
                sh '''
                    dotnet --list-sdks
                    dotnet --list-runtimes
                '''
            }
        }
    }
}